on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
name: Build robot
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11, 17 ]
    name: Java ${{ matrix.java }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3.5.2
      - name: Setup java
        uses: actions/setup-java@v3.11.0
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
      - run: ./mvnw -B -T1C verify
