on:
  push:
    tags:
    - 'v*'

name: Release robot

jobs:
  build:
    name: Upload release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Setup Java
        uses: actions/setup-java@v3.11.0
        with:
          java-version: 11
          distribution: temurin
      - name: Set SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: Add known host key
        run: ssh-keyscan javacard.pro >> ~/.ssh/known_hosts
      - name: Package
        run: ./mvnw -B -T1C verify
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
      - name: Deploy package
        run: ./mvnw -B -T1C deploy
