on:
  push:
    tags:
    - 'v*'

name: Release CI

jobs:
  build:
    name: Upload release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Setup Java
        uses: actions/setup-java@v3.4.1
        with:
          java-version: 11
          distribution: temurin
      - name: Set SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: Add known host key
        run: ssh-keyscan javacard.pro >> ~/.ssh/known_hosts
      - name: Package
        run: ./mvnw -B -T1C verify
      - name: Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: true # Manually promoted to latest release
      - name: Deploy package
        run: ./mvnw -B -T1C deploy
