on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
    branches:
      - master
      - next
  pull_request:
    branches:
      - next
name: Build robot
concurrency:
  group: robot
  cancel-in-progress: false
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        java: [ 17, 21, 25 ]
    name: Java ${{ matrix.java }}
    env:
      PUBLISH: ${{ matrix.java == '17' && ( github.ref == 'refs/heads/master' || github.ref == 'refs/heads/next' || startsWith(github.ref, 'refs/tags/v') ) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0 # To make git describe give the intended output
          fetch-tags: true
      - name: Setup java
        uses: actions/setup-java@v6
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: maven
      - name: Set up publishing
        if: env.PUBLISH == 'true'
        uses: martinpaljak/maven-ssh-deploy@v2
        with:
          host: mvn.javacard.pro
          key: ${{ secrets.SSH_KEY }}
          fingerprint: SHA256:auiF3nHWvDmvq2stDl+QEECCqMcDp+FY1/bDRnvxpRw
      - name: Build and deploy
        run: ./mvnw -B -U deploy -Dmaven.deploy.skip=${{ env.PUBLISH != 'true' }}
  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Release
        uses: softprops/action-gh-release@v3.0.3
        with:
          body: Release ${{ github.ref_name }}
          prerelease: true # manually promoted
