on:
  push:
    tags:
      - 'v*'
    branches:
      - master
      - next
  pull_request:
    branches:
      - master
name: Build robot
jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        java: [ 17, 21, 25]
    name: Java ${{ matrix.java }}
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # To make git describe give the intended output
          fetch-tags: true
      - name: Setup java
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: maven
      - name: Build
        run: ./mvnw -T1C -B --no-transfer-progress -U verify
      - name: Deploy package or snapshot
        if: github.event_name != 'pull_request' && matrix.java == '17'
        uses: martinpaljak/maven-ssh-deploy@v1
        with:
          key: ${{ secrets.SSH_KEY }}
          user: mvn@mvn.javacard.pro
          host_fp: SHA256:auiF3nHWvDmvq2stDl+QEECCqMcDp+FY1/bDRnvxpRw
      - name: Release
        if: startsWith(github.ref, 'refs/tags/v') && matrix.java == '17'
        id: create_release
        uses: softprops/action-gh-release@v2.5.0
        with:
          body: "Release ${{ github.ref_name }}"
          prerelease: true # manually promoted
