on:
  push:
    tags:
      - 'v*'
    branches:
      - master
      - next
  pull_request:
    branches:
      - master
name: Robot builder
jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        java: [ 11, 17, 21 ]
    name: Java ${{ matrix.java }}
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v4.2.0
        with:
          fetch-depth: 0 # To make git describe give the intended output
          fetch-tags: true
      - name: Setup java
        uses: actions/setup-java@v4.4.0
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: maven
      - name: Set SSH key
        if: github.event_name != 'pull_request'
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: Add host key
        if: github.event_name != 'pull_request'
        run: ssh-keyscan javacard.pro >> ~/.ssh/known_hosts
      - name: Build
        run: ./mvnw -T1C -B -U verify
      - name: Deploy package or snapshot
        if: github.event_name != 'pull_request' && matrix.java == '11'
        run: ./mvnw -B -U deploy
      - name: Release
        if: startsWith(github.ref, 'refs/tags/v') && matrix.java == '11'
        id: create_release
        uses: softprops/action-gh-release@v2.0.8
        with:
          body: "Release ${{ github.ref_name }}"
          prerelease: true # manually promoted
